version: "3"

services:
  service-a:
    image: node-service-a
    ports:
      - "3000:3000"
  service-b:
    image: node-service-b
    ports:
      - "3001:3001"
  database:
    image: mongo
    # ports:
    #   - ""
